primera parte/funx-front/config/routes.rb
Rails.application.routes.draw do

  root "tops#top"

  resources :albums
  resources :artists
  get 'top', to: 'tops#top'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

primera parte/funx-front/app/models/album.rb
class Album
  include ApiClient

  ALBUM_BASE = '/albums'.freeze

  attr_accessor :id, :name, :reproductions, :artist_id

  def initialize(params = {})
    self.id = params[:id]
    self.name = params[:name]
    self.reproductions = params[:reproductions]
    self.artist_id = params[:artist_id]
  end

  def self.all
    get_json("#{MAIN_URL}#{ALBUM_BASE}")
  end

  def self.find(album_id)
    Album.new(get_json("#{MAIN_URL}#{ALBUM_BASE}/#{album_id}"))
  end

  def save
    response = Album.post_json("#{MAIN_URL}#{ALBUM_BASE}", album_params)
    self.id = response.id
  end

  def update(params)
    Album.put_json("#{MAIN_URL}#{ALBUM_BASE}/#{id}", { album: params.to_h })
  end

  def destroy
    Album.delete_json("#{MAIN_URL}#{ALBUM_BASE}/#{id}")
  end

  private

  def album_params
    {album: {id: id, name: name, reproductions: reproductions, artist_id: artist_id}}
  end


  #post_json("#{MAIN_URL}#{ALBUM_BASE}", album_params)

end

primera parte/funx-front/app/models/api_client.rb
module ApiClient
  extend ActiveSupport::Concern

  included do
    require 'ostruct'

    MAIN_URL = 'localhost:3000/api/v1'.freeze

    def self.get_json(url)
      request_json(url, :get)
    end

    def self.post_json(url, params)
      request_json(url, :post, params)
    end

    def self.put_json(url, params)
      request_json(url, :put, params)
    end

    def self.delete_json(url)
      RestClient.try(:delete, url)
    end

    private
    def self.request_json(url, method, params = {})
      response = RestClient.try(method, url, params)
      JSON.parse(response.body, object_class: OpenStruct)
    end

  end
end

primera parte/funx-front/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

primera parte/funx-front/app/models/artist.rb
class Artist
  include ApiClient

  BASE = '/artists'.freeze

  attr_accessor :id, :name

  def initialize(params = {})
    self.id = params[:id]
    self.name = params[:name]
  end

  def self.all
    get_json("#{MAIN_URL}#{BASE}")
  end

  def self.find(artist_id)
    Artist.new(get_json("#{MAIN_URL}#{BASE}/#{artist_id}"))
  end

  def save
    response = Artist.post_json("#{MAIN_URL}#{BASE}", artist_params)
    self.id = response.id
  end

  def update(params)
    Artist.put_json("#{MAIN_URL}#{BASE}/#{id}", { artist: params.to_h })
  end

  def destroy
    Artist.delete_json("#{MAIN_URL}#{BASE}/#{id}")
  end

  private

  def artist_params
    {artist: {id: id, name: name}}
  end
end

primera parte/funx-front/app/models/top.rb
class Top
  include ApiClient
  BASE = '/top'.freeze
  def self.top_ten
    get_json("#{MAIN_URL}#{BASE}")
  end
end

primera parte/funx-front/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to album_path(@album.id), notice: 'Album fue creado.' }
      else
        format.html { render albums_path, alert: 'No se pudo crear' }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to album_path(@album.id), notice: 'Album was successfully updated.' }
      else
        format.html { render edit_album_path(@album.id) }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name, :reproductions, :artist_id)
    end
end

primera parte/funx-front/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

primera parte/funx-front/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to artist_path(@artist.id), notice: 'Artist was successfully created.' }
      else
        format.html { render new_artist_path }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to artist_path(@artist.id), notice: 'Artist was successfully updated.' }
      else
        format.html { render edit_artist_path }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name)
    end
end

primera parte/funx-front/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def welcome
  end
end

primera parte/funx-front/app/controllers/tops_controller.rb
class TopsController < ApplicationController

  def top
    @artists = Top.top_ten
  end
end

primera parte/funx-front/app/helpers/albums_helper.rb
module AlbumsHelper
end

primera parte/funx-front/app/helpers/application_helper.rb
module ApplicationHelper
end

primera parte/funx-front/app/helpers/artists_helper.rb
module ArtistsHelper
end

primera parte/funx-front/app/helpers/pages_helper.rb
module PagesHelper
end

primera parte/funx-front/app/helpers/tops_helper.rb
module TopsHelper
end

primera parte/funx-front/app/views/albums/_form.html.erb
<%= form_for(:album, url: album.id ? "/albums/#{album.id}" : '/albums') do |form| %>
  <% if album.id %>
    <input name="_method" type="hidden" value="put" />
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :reproductions %>
    <%= form.number_field :reproductions %>
  </div>

  <div class="field">
    <%= form.label :artist_id %>
    <small>(debe existir el id)</small>
    <%= form.number_field :artist_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

primera parte/funx-front/app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Show', album_path(@album.id) %> |
<%= link_to 'Back', albums_path %>

primera parte/funx-front/app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>
<div class="table-wrapper">
  <div class="table-title">
    <div class="row">
      <div class="col-sm-6">
        <h2>Albumes</h2>
      </div>
    </div>
  </div>
  <table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Reproductions</th>
      <th>Artist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.name %></td>
        <td><%= album.reproductions %></td>
        <td><%= album.artist_id %></td>
        <td><%= link_to 'Ver', album_path(album.id) %></td>
        <td><%= link_to 'Edit', edit_album_path(album.id) %></td>
        <td><%= button_to 'Destroy', album_path(album.id), method: :delete, data: { confirm: 'Are you sure?' }%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>
</div>

primera parte/funx-front/app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Back', albums_path %>

primera parte/funx-front/app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @album.name %>
</p>

<p>
  <strong>Reproductions:</strong>
  <%= @album.reproductions %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @album.artist_id %>
</p>

<%= link_to 'Edit', edit_album_path(@album.id) %> |
<%= link_to 'Back', albums_path %>

primera parte/funx-front/app/views/artists/_form.html.erb
<%= form_for(:artist, url: artist.id ? "/artists/#{artist.id}" : '/artists') do |form| %>
  <% if artist.id %>
    <input name="_method" type="hidden" value="put" />
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

primera parte/funx-front/app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', artists_path(@artist.id) %> |
<%= link_to 'Back', artists_path %>

primera parte/funx-front/app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>
<div class="table-wrapper">
  <div class="table-title">
    <div class="row">
      <div class="col-sm-6">
        <h2>Artistas</h2>
      </div>
    </div>
  </div>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>id</th>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @artists.each do |artist| %>
        <tr>
          <td><%= artist.id %></td>
          <td><%= artist.name %></td>
          <td><%= link_to 'Ver', artist_path(artist.id) %></td>
          <td><%= link_to 'Edit', edit_artist_path(artist.id) %></td>
          <td><%= button_to 'Destroy', artist_path(artist.id), method: :delete, data: { confirm: 'Are you sure?' }%></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Artist', new_artist_path %>
</div>

primera parte/funx-front/app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path %>

primera parte/funx-front/app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<%= link_to 'Edit', edit_artist_path(@artist.id) %> |
<%= link_to 'Back', artists_path %>

primera parte/funx-front/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FunxFront</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    
    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }
  </style>

  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">FunxFront</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <li><%= link_to "Albumes", albums_path %></li>
            <li><%= link_to "Artistas", artists_path %></li>
            <li class="active"><%= link_to "Grafico Top", top_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

primera parte/funx-front/app/views/pages/welcome.html.erb
<h1>Funx Artists</h1>

<div>
  <%= link_to "Albumes", albums_path %>
  <%= link_to "Artistas", artists_path %>
  <%= link_to "Grafico Top", top_path %>
</div>

primera parte/funx-front/app/views/tops/top.html.erb
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
<canvas id="myChart"></canvas>

<script type="text/javascript">
var ctx = document.getElementById('myChart').getContext('2d');
var chart = new Chart(ctx, {
    // The type of chart we want to create
    type: 'bar',

    // The data for our dataset
    data: {
        labels: <%=  raw @artists.map(&:name) %>,
        datasets: [{
            label: 'reproductions',
            backgroundColor: 'rgb(255, 99, 132)',
            borderColor: 'rgb(255, 99, 132)',
            data: <%=  raw @artists.map(&:reproductions) + [0] %>,
        }]
    },

    // Configuration options go here
    options: {}
});
</script>